# Generated by Django 6.0.1 on 2026-07-28 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0035_provincial_admin_architecture'),
        ('super_admin', '0002_facultyreport_universityreport_delete_academicreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvincialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('academic_year', models.CharField(default='2023-2024', max_length=20)),
                ('total_universities', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('passed_students', models.IntegerField(default=0)),
                ('failed_students', models.IntegerField(default=0)),
                ('universities_reported', models.IntegerField(default=0)),
                ('universities_pending', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_validated', models.BooleanField(default=False, help_text='Validé par le Super-Admin ministériel')),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincial_reports', to='lms.province')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_provincial_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TerritorialAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('FAILURE_SPIKE', "Hausse anormale du taux d'échec"), ('REPORT_LATE', 'Retard de dépôt de rapport'), ('SEMESTER_LOCK', 'Retard de clôture de session'), ('LMD_NONCOMPLIANCE', 'Non-conformité LMD'), ('OTHER', 'Autre anomalie')], default='OTHER', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territorial_alerts', to='lms.province')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='territorial_alerts', to='lms.university')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
