# Generated by Django 6.0.1 on 2026-08-01 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0041_grade_flow_dean_then_manager'),
        ('super_admin', '0003_provincial_admin_architecture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterResultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')])),
                ('academic_year', models.CharField(default='2025-2026', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('credits_reference', models.PositiveIntegerField(default=60, help_text='Référence LMD annuelle (60 crédits)')),
                ('total_students', models.IntegerField(default=0)),
                ('passed_students', models.IntegerField(default=0)),
                ('failed_students', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_result_reports', to='lms.faculty')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_result_reports', to='lms.promotion')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_semester_reports', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_result_reports', to='lms.university')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SemesterResultLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('promotion_label', models.CharField(max_length=64)),
                ('faculty_label', models.CharField(max_length=255)),
                ('credits_earned', models.PositiveIntegerField(default=0)),
                ('credits_total', models.PositiveIntegerField(default=60)),
                ('result', models.CharField(choices=[('REUSSITE', 'Réussite'), ('ECHEC', 'Échec')], max_length=20)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_result_lines', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='super_admin.semesterresultreport')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
