# Generated by Django 6.0.1 on 2026-08-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0004_grade_flow_dean_then_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterresultline',
            name='s1_credits_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semesterresultline',
            name='s1_credits_total',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='semesterresultline',
            name='s2_credits_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semesterresultline',
            name='s2_credits_total',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='semesterresultreport',
            name='semester_credits_reference',
            field=models.PositiveIntegerField(default=30, help_text='Référence par semestre (30 crédits)'),
        ),
        migrations.AlterField(
            model_name='semesterresultline',
            name='credits_earned',
            field=models.PositiveIntegerField(default=0, help_text='Total annuel S1+S2'),
        ),
        migrations.AlterField(
            model_name='semesterresultreport',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Semestre 1'), (2, 'Semestre 2')], help_text='Null = rapport annuel consolidé S1+S2', null=True),
        ),
    ]
