# Generated by Django 4.2.11 on 2026-04-16 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_lessonfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='lms.coursecomment'),
        ),
        migrations.AddField(
            model_name='lessoncomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='lms.lessoncomment'),
        ),
    ]
