# Generated by Django 4.2.11 on 2026-04-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_coursecomment_parent_lessoncomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('course', 'Nouveau Cours'), ('grade', 'Note'), ('reply', 'Réponse'), ('grade', 'Note'), ('reminder', 'Rappel'), ('system', 'Système')], default='system', max_length=20),
        ),
    ]
