# Generated by Django 4.2.11 on 2026-05-08 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_quiz_quizquestion_quizchoice_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='id_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
