# Generated by Django 4.2.11 on 2026-05-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_externalresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='courses/thumbnails/'),
        ),
        migrations.AddField(
            model_name='externalresource',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='external_resources/thumbnails/'),
        ),
    ]
