# Generated by Django 4.2.11 on 2026-05-19 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_faculty_university_promotion_faculty_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='universities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='university',
            unique_together={('name', 'teacher')},
        ),
    ]
