# Generated by Django 6.0.1 on 2026-05-22 20:59

import lms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_university_teacher_alter_university_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/', validators=[lms.models.validate_lesson_file]),
        ),
    ]
