# Generated by Django 6.0.1 on 2026-06-11 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_alter_lesson_content_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_teachers', to='lms.faculty'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_teachers', to='lms.promotion'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_teachers', to='lms.university'),
        ),
    ]
