# Generated by Django 6.0.1 on 2026-06-11 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0019_nationalcourse_alter_quiz_options_course_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisite_quiz',
            field=models.ForeignKey(blank=True, help_text='Quiz à réussir (50%) pour débloquer ce cours', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_courses', to='lms.quiz'),
        ),
    ]
