# Generated by Django 6.0.1 on 2026-06-11 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0020_course_prerequisite_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('BAS_UELE', 'Bas-Uélé'), ('EQUATEUR', 'Équateur'), ('HAUT_KATANGA', 'Haut-Katanga'), ('HAUT_LOMAMI', 'Haut-Lomami'), ('HAUT_UELE', 'Haut-Uélé'), ('ITURI', 'Ituri'), ('KASAI', 'Kasaï'), ('KASAI_CENTRAL', 'Kasaï-Central'), ('KASAI_ORIENTAL', 'Kasaï-Oriental'), ('KINSHASA', 'Kinshasa'), ('KONGO_CENTRAL', 'Kongo-Central'), ('KWANGO', 'Kwango'), ('KWILU', 'Kwilu'), ('LOMAMI', 'Lomami'), ('LUALABA', 'Lualaba'), ('MANIEMA', 'Maniema'), ('MAI_NDOMBE', 'Maï-Ndombe'), ('MONGALA', 'Mongala'), ('NORD_KIVU', 'Nord-Kivu'), ('NORD_UBANGI', 'Nord-Ubangi'), ('SANKURU', 'Sankuru'), ('SUD_KIVU', 'Sud-Kivu'), ('SUD_UBANGI', 'Sud-Ubangi'), ('TANGANYIKA', 'Tanganyika'), ('TSHOPO', 'Tshopo'), ('TSHUAPA', 'Tshuapa')], max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='university',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universities', to='lms.province'),
        ),
    ]
