# Generated by Django 6.0.1 on 2026-06-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0021_province_university_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='session',
            field=models.CharField(choices=[('1ere', '1ère Session'), ('2eme', '2ème Session (Rattrapage)')], default='1ere', max_length=10),
        ),
    ]
