# Generated by Django 6.0.1 on 2026-06-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0022_quizattempt_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='is_grading_locked',
            field=models.BooleanField(default=False, help_text="Verrouille la saisie et modification des notes pour tout l'établissement"),
        ),
    ]
