# Generated by Django 4.2.11 on 2026-06-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0023_university_is_grading_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('SIMPLE', "Exercice d'entraînement"), ('EVALUATION', 'Quiz de validation (bloquant)')], default='EVALUATION', max_length=20),
        ),
    ]
