# Generated by Django 4.2.11 on 2026-07-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0025_coursegrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalcourse',
            name='semester',
            field=models.IntegerField(choices=[(1, '1er Semestre'), (2, '2ème Semestre')], default=1),
        ),
    ]
