# Generated by Django 4.2.11 on 2026-07-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0026_nationalcourse_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[(1, '1er Semestre'), (2, '2ème Semestre')], default=1),
        ),
        migrations.AddField(
            model_name='university',
            name='s1_closed',
            field=models.BooleanField(default=False, help_text='Clôture et bloque le 1er semestre au niveau établissement'),
        ),
        migrations.AddField(
            model_name='university',
            name='s2_closed',
            field=models.BooleanField(default=False, help_text='Clôture et bloque le 2ème semestre au niveau établissement'),
        ),
    ]
