# Generated by Django 6.0.1 on 2026-07-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0029_studentaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaudit',
            name='full_name',
            field=models.CharField(blank=True, help_text="Nom complet défini par l'enseignant", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentaudit',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon Enseignant'), ('SUBMITTED_TO_MANAGER', 'Soumis au Gestionnaire')], default='DRAFT', max_length=30),
        ),
    ]
