# Generated by Django 6.0.1 on 2026-07-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0030_studentaudit_full_name_studentaudit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_semester',
            field=models.IntegerField(blank=True, choices=[(1, '1er Semestre'), (2, '2ème Semestre')], null=True),
        ),
    ]
