# Generated by Django 6.0.1 on 2026-07-12 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0031_user_assigned_semester'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentaudit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentaudit',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='lms.course'),
        ),
        migrations.AlterUniqueTogether(
            name='studentaudit',
            unique_together={('student', 'teacher', 'course')},
        ),
    ]
