# Generated by Django 6.0.1 on 2026-07-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0032_alter_studentaudit_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrateur (Ministère)'), ('MANAGER', 'Gestionnaire (Petit Admin)'), ('DEAN', 'Décanat (Faculté)'), ('TEACHER', 'Enseignant'), ('STUDENT', 'Étudiant')], default='STUDENT', max_length=20),
        ),
    ]
