# Generated by Django 6.0.1 on 2026-07-28 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0034_quiz_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'universities'},
        ),
        migrations.AddField(
            model_name='university',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='university',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text="Capacité d'accueil estimée", null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='university',
            name='institution_type',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Privé')], default='PUBLIC', max_length=10),
        ),
        migrations.AddField(
            model_name='university',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_province',
            field=models.ForeignKey(blank=True, help_text="Province de tutelle pour l'Administrateur Provincial", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provincial_admins', to='lms.province'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrateur (Ministère)'), ('PROVINCIAL_ADMIN', 'Administrateur Provincial'), ('MANAGER', 'Gestionnaire (Université)'), ('DEAN', 'Décanat (Faculté)'), ('TEACHER', 'Enseignant'), ('STUDENT', 'Étudiant')], default='STUDENT', max_length=20),
        ),
    ]
