# Generated by Django 6.0.1 on 2026-07-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0035_provincial_admin_architecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, db_index=True, help_text='UID Firebase Auth — utilisé pour le chat temps réel', max_length=128, null=True),
        ),
    ]
