# Generated by Django 6.0.1 on 2026-07-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0036_user_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_promotions',
            field=models.ManyToManyField(blank=True, help_text='Promotions que le décanat peut confier à cet enseignant.', related_name='multi_assigned_teachers', to='lms.promotion'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('teacher', 'national_course', 'promotion'), name='unique_teacher_national_course_promotion'),
        ),
    ]
