# Generated by Django 6.0.1 on 2026-07-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0037_user_assigned_promotions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(choices=[('L1', 'L1 (Licence 1)'), ('L2', 'L2 (Licence 2)'), ('L3', 'L3 (Licence 3)'), ('M1', 'M1 (Master 1)'), ('M2', 'M2 (Master 2)')], help_text='Niveau LMD (L1 à M2)', max_length=10),
        ),
    ]
