# Generated by Django 6.0.1 on 2026-07-30 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0038_promotion_lmd_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'national faculties',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='nationalcourse',
            options={'ordering': ['national_faculty__name', 'semester', 'code']},
        ),
        migrations.AlterField(
            model_name='nationalcourse',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='faculty',
            name='national_faculty',
            field=models.ForeignKey(blank=True, help_text='Correspondance avec le référentiel national de facultés.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_faculties', to='lms.nationalfaculty'),
        ),
        migrations.AddField(
            model_name='nationalcourse',
            name='national_faculty',
            field=models.ForeignKey(blank=True, help_text='Faculté nationale à laquelle ce cours est rattaché.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='lms.nationalfaculty'),
        ),
        migrations.AddConstraint(
            model_name='nationalcourse',
            constraint=models.UniqueConstraint(fields=('national_faculty', 'code'), name='unique_national_course_code_per_faculty'),
        ),
    ]
