# Generated by Django 6.0.1 on 2026-07-30 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0039_national_faculty_and_course_scope'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_teacher_national_course_promotion',
        ),
        migrations.AddField(
            model_name='course',
            name='assigned_to_dean',
            field=models.ForeignKey(blank=True, help_text='Décanat destinataire (attribué par le Manager).', limit_choices_to={'role': 'DEAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Manager ayant créé le cours.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.PositiveIntegerField(default=1, help_text='Crédits ECTS du cours (définis par le Manager).'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Enseignant titulaire (attribué par le Décanat).', limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(condition=models.Q(('teacher__isnull', False)), fields=('teacher', 'title', 'promotion'), name='unique_teacher_title_promotion_assigned'),
        ),
    ]
