# Generated by Django 6.0.1 on 2026-08-01 23:52

from django.db import migrations, models


def migrate_submitted_to_dean(apps, schema_editor):
    """Les cotes déjà soumises au Manager deviennent destinées au Décanat."""
    StudentAudit = apps.get_model('lms', 'StudentAudit')
    CourseGrade = apps.get_model('lms', 'CourseGrade')
    StudentAudit.objects.filter(status='SUBMITTED_TO_MANAGER').update(status='SUBMITTED_TO_DEAN')
    CourseGrade.objects.filter(status='SUBMITTED_TO_MANAGER').update(status='SUBMITTED_TO_DEAN')


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0040_course_manager_dean_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon Enseignant'), ('SUBMITTED_TO_DEAN', 'Soumis au Décanat'), ('SUBMITTED_TO_MANAGER', 'Soumis au Gestionnaire (historique)'), ('VALIDATED_BY_DEAN', 'Validé par le Décanat'), ('APPROVED', 'Approuvé / Consolidé'), ('SUBMITTED_TO_MINISTRY', 'Soumis au Ministère (Verrouillé)')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentaudit',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon Enseignant'), ('SUBMITTED_TO_DEAN', 'Soumis au Décanat'), ('SUBMITTED_TO_MANAGER', 'Soumis au Gestionnaire (historique)'), ('VALIDATED_BY_DEAN', 'Validé par le Décanat')], default='DRAFT', max_length=30),
        ),
        migrations.RunPython(migrate_submitted_to_dean, migrations.RunPython.noop),
    ]
