# Generated by Django 6.0.1 on 2026-09-27 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0043_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='assigned_to_dean',
            field=models.ForeignKey(blank=True, help_text='Décanat propriétaire du cours (créateur / responsable facultaire).', limit_choices_to={'role': 'DEAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant créé le cours (Décanat).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.PositiveIntegerField(default=1, help_text='Crédits ECTS du cours (définis par le Décanat).'),
        ),
        migrations.AlterField(
            model_name='coursegrade',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon Enseignant'), ('SUBMITTED_TO_DEAN', 'Soumis au Décanat'), ('SUBMITTED_TO_MANAGER', "Soumis à l'Admin (Université) (historique)"), ('VALIDATED_BY_DEAN', 'Validé par le Décanat'), ('APPROVED', 'Approuvé / Consolidé'), ('SUBMITTED_TO_MINISTRY', 'Soumis au Ministère (Verrouillé)')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentaudit',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon Enseignant'), ('SUBMITTED_TO_DEAN', 'Soumis au Décanat'), ('SUBMITTED_TO_MANAGER', "Soumis à l'Admin (Université) (historique)"), ('VALIDATED_BY_DEAN', 'Validé par le Décanat')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrateur (Ministère)'), ('PROVINCIAL_ADMIN', 'Administrateur Provincial'), ('MANAGER', 'Admin (Université)'), ('DEAN', 'Décanat (Faculté)'), ('TEACHER', 'Enseignant'), ('STUDENT', 'Étudiant')], db_index=True, default='STUDENT', max_length=20),
        ),
    ]
